name: SimpleNBT
main: org.cubeville.cvtools.CVTools
author: KipperOrigin
version: 0.1

softdepend: [ProtocolLib]

commands:
  snbt:
    description: Base Command
    
permissions:
  snbt.admin:
    description: Gives player access to every command.
    default: op